- packages/dev/src/CustomCatalog.tsx
- packages/module/src/catalog/QuickStartCatalog.scss
- packages/module/src/catalog/QuickStartCatalog.tsx
- packages/module/src/catalog/QuickStartTile.tsx
Fixes: https://issues.redhat.com/browse/ODC-6091
This PR fixes the issue wherein clicking on prerequisites popover, quickstart sidebar was getting closed if open and getting open if closed. It was because the popover click event was getting propagated to the tile and hence its onClick handler was getting executed. Fixed this issue by checking if the clicked element is inside the tile and if yes then only open/close the sidebar.
https://user-images.githubusercontent.com/20724543/124779970-da29ed00-df5f-11eb-9540-a943642008a3.mov
> Fix QuickStartTile's onClick handler

- packages/module/src/QuickStartPanelContent.scss
- packages/module/src/QuickStartPanelContent.tsx
**Fixes:**
https://issues.redhat.com/browse/ODC-6159
This PR restore a shadow which was earlier shown in the QuickStart content when the user can scroll the content in a small window (or with a long content). This is similar to OpenShift console issue https://github.com/openshift/console/pull/9527
**Before (main):**
**After (with this PR):**
> Fix missing shadow when user can scroll content

- packages/dev/package.json
- packages/dev/src/quickstarts-data/mocks/yamls/add-healthchecks-quickstart.yaml
- packages/module/package.json
- packages/module/src/controller/QuickStartConclusion.tsx
- packages/module/src/controller/QuickStartContent.tsx
- packages/module/src/controller/__tests__/QuickStartConclusion.spec.tsx
Example ^
Towards https://github.com/patternfly/patternfly-quickstarts/issues/30
> support multiple next quick start links in conclusion

- packages/module/src/controller/QuickStartFooter.tsx
- packages/module/src/controller/__tests__/QuickStartFooter.spec.tsx
Closes #28 
After clicking the restart `link` that appears on the bottom right, or after starting a QS then clicking back, the restart `button` appears to the right of the continue button, but still in the bottom left. To me it should be removed when the continue button is there, but possibly I am missing its use case.
For clarity this is the restart link which will appear on every screen except the initial one:
> feat(QuickStartFooter): always show restart action in footer

- packages/dev/package.json
- packages/dev/src/common/Page.tsx
- packages/dev/src/index.tsx
- packages/dev/webpack.config.js
- packages/module/README.md
- packages/module/package.json
- packages/module/purgecss.config.js
- packages/module/rollup.config.js
- packages/module/src/ConsoleShared/src/components/markdown-extensions/MarkdownCopyClipboard.tsx
- packages/module/src/ConsoleShared/src/components/popper/SimplePopper.tsx
- packages/module/src/QuickStartCatalogPage.tsx
- packages/module/src/QuickStartCloseModal.tsx
- packages/module/src/QuickStartDrawer.tsx
- packages/module/src/QuickStartPanelContent.tsx
- packages/module/src/catalog/QuickStartCatalog.tsx
- packages/module/src/catalog/QuickStartTileDescription.tsx
- packages/module/src/controller/QuickStartContent.scss
- packages/module/src/styles/_base.scss
- packages/module/src/styles/legacy-bootstrap/README.md
- packages/module/src/styles/patternfly-global-entry.ts
- packages/module/src/styles/patternfly-global.scss
- packages/module/src/styles/patternfly-nested-entry.ts
- packages/module/src/styles/patternfly-nested.scss
- packages/module/src/styles/quickstarts-standalone-entry.ts
- packages/module/src/styles/quickstarts-standalone.scss
- packages/module/src/styles/style.scss
- packages/module/src/styles/vendor.scss
- packages/transform-adoc/src/react-converter/util.scss
- snapshots.js
- yarn.lock
Creates new stylesheets:
```js
// some global styles and variables that quickstarts uses (Drawer, Popover, Modal, Backdrop, Bullseye)
import '@patternfly/quickstarts/dist/patternfly-global.css';
// PF and quickstarts styles nested within .pfext-quick-start__base
import '@patternfly/quickstarts/dist/quickstarts-standalone.min.css';
```
These are useful if a consumer uses an older version of PatternFly for instance
> Quickstarts standalone

- packages/module/README.md
- packages/module/src/QuickStartDrawer.tsx
- packages/module/src/utils/quick-start-context.tsx
In the case that a product's UI clashes with drawer header color update to blue with white text:
- default to blue/white
- add boolean option to opt-out of these changes
Closes: #95
> Add configuration to opt-out of new header colors

- packages/dev/src/App3.tsx
- packages/dev/src/Demos.ts
- packages/dev/src/index.tsx
- packages/dev/src/quickstarts-data/localized-data/cs/demo.yaml
- packages/dev/src/quickstarts-data/localized-data/en/demo.yaml
- packages/dev/src/quickstarts-data/quick-start-test-data.ts
- packages/module/README.md
- packages/module/src/ConsoleInternal/module/k8s/types.ts
- packages/module/src/QuickStartCatalogPage.tsx
Closes #93 
So I didn't put the filtering based on the language inside the library. We are gonna leave it for the consumer, they can filter it how they want it (more flexibility).
I added a new demo under /quickstart-localized to demonstrate how it can be done.
> Adds language and countryCode keys and creates new localization demo

- packages/module/src/QuickStartCatalogPage.tsx
We require the catalog page props in some of the chrome integration work when providing the API to the micro frontends.
cc @jschuler @CooperRedhat
> Export catalog page props.

- packages/module/src/QuickStartPanelContent.tsx
- packages/module/src/locales/en/quickstart.json
Closes https://github.com/patternfly/patternfly-quickstarts/issues/109
Default:
No durationMinutes:
When overriding the `Type` resource:
```
resourceBundle: {
...resourceBundle,
Type: 'Documentation',
},
```
When overriding the `Type` resource and not specifying durationMinutes:
> optional duration

- packages/dev/src/quickstarts-data/asciidoc/alert-note-prereq/README.adoc
- packages/dev/src/quickstarts-data/asciidoc/alert-note-prereq/quickstart.yml
- packages/dev/src/quickstarts-data/asciidoc/procedure-parser.ts
- packages/transform-adoc/src/react-converter/add-react-converter.tsx
- packages/transform-adoc/src/react-converter/util.scss
- packages/transform-adoc/src/react-converter/util.tsx
Closes #105 
Also solves issue where only the final newline separated string (or `.adoc` block) was rendered in description.
> support all admonitions, concat description blocks

- packages/dev/src/quickstarts-data/yaml/template.yaml
- packages/module/src/ConsoleShared/src/components/markdown-extensions/admonition-extension.tsx
- packages/module/src/ConsoleShared/src/components/markdown-extensions/index.ts
- packages/module/src/ConsoleShared/src/components/markdown-extensions/showdown-extension.scss
- packages/module/src/QuickStartMarkdownView.tsx
Closes #118
Showdown extension for admonitions
- uses similar syntax to highlight extension
- i.e. `[Alert/Admonition text content]{{admonition warning}}`
- Added updated `Getting started with quick starts` yaml with examples
- [Examples in yaml ](https://github.com/patternfly/patternfly-quickstarts/blob/2f1fc3a21041406504d8c9aa1947367963fe6e58/packages/dev/src/quickstarts-data/yaml/template.yaml#L74)
> Add showdown extension for admonitions through markdown syntax

- packages/dev/src/AppLocalized.tsx
- packages/dev/src/AppProps.tsx
- packages/dev/src/quickstarts-data/yaml/add-healthchecks-quickstart.yaml
- packages/dev/src/quickstarts-data/yaml/template.yaml
- packages/module/src/ConsoleInternal/components/markdown-view.tsx
- packages/module/src/QuickStartDrawer.tsx
- packages/module/src/QuickStartPanelContent.scss
- packages/module/src/catalog/QuickStartTile.tsx
- packages/module/src/controller/QuickStartIntroduction.tsx
- packages/module/src/controller/QuickStartTaskHeader.tsx
- packages/module/src/controller/QuickStartTasks.scss
- packages/module/src/styles/_base.scss
- packages/module/src/utils/quick-start-context.tsx
Closes https://github.com/patternfly/patternfly-quickstarts/issues/142 https://github.com/patternfly/patternfly-quickstarts/issues/138 https://github.com/patternfly/patternfly-quickstarts/issues/130 https://github.com/patternfly/patternfly-quickstarts/issues/104 https://github.com/patternfly/patternfly-quickstarts/issues/132
Partially addresses https://github.com/patternfly/patternfly-quickstarts/issues/125
- Links in the introduction prerequisites are now rendered
- Links in the catalog tile card popover now work on left click (opens new tab)
- Restart action in the drawer properly resets the quick start
- Toned down frequency at which the Failed task sub heading is shown
- Reduced spacing
Regarding the links issues, I added some sample links to this item …
> handle prereq links, fix spacing a bit

- packages/dev/src/MockConsole.tsx
- packages/module/src/HelpTopicDrawer.tsx
- packages/module/src/HelpTopicPanelContent.tsx
- packages/module/src/utils/help-topic-context.tsx
- Reintroduce close button
- Update styles to align paragraph and title
- Remove hamburger dropdown if filteredHelpTopics not set or empty
- Add example to modify closing behavior
- Auto update HelpTopicContainer when helpTopics change
Closes #149, towards #150 
Closes #151
Closes #154
> [HelpTopics] Styling, hamburger menu, close behavior example, etc.

- packages/dev/src/quickstarts-data/yaml/in-context-help/example-topics.yaml
- packages/module/package.json
- packages/module/src/HelpTopicPanelContent.tsx
- packages/module/src/utils/help-topic-types.ts
- Remove divider if there are no links present in a HelpTopic
- Links now optional
> [HelpTopics] handle empty links, make optional, add test yaml

- packages/dev/src/quickstarts-data/yaml/template.yaml
- packages/module/src/ConsoleShared/src/components/markdown-extensions/MarkdownCopyClipboard.tsx
- packages/module/src/ConsoleShared/src/components/markdown-extensions/inline-clipboard-extension.tsx
- packages/module/src/ConsoleShared/src/components/markdown-extensions/multiline-clipboard-extension.tsx
This PR https://github.com/patternfly/patternfly-quickstarts/pull/186 incorrectly updated the inline copy to use the updated multiline copy regex.
This PR fixes that. Also noticed that the copy blocks were not receiving the correct IDs, so if there were multiple copy blocks within the same page, only the content of the first copy block was copied on the other ones.
> Fix copy actions

- packages/module/src/utils/quick-start-context.tsx
In the OpenShift Console, we missed some translations in our resource bundle. Also, the English ResourceBundle missed some translations from this package.
In this case, the UI doesn't show _anything_ because `getResource` returns an empty string if the translation isn't found in the ResourceBundle.
In this case, `getResource` should return the input `resource` string instead so that the UI shows _something_. If just the translation is missing it shows at least an English version.
> getResource doesn't shown anything if translation string is missing in the ResourceBundle (incl. English)

- packages/module/src/HelpTopicPanelContent.tsx
The help topic panel provides a dropdown menu to switch between topics that are currently available. However if there is only a single topic available, this menu is of no use.
This change removes the menu unless there are 2 or more help topics.
Before:
After:
> show help topic menu when there is more than one help topic

- packages/module/src/styles/_dark-custom-override.scss
> Exclude markdown pre black background for code blocks

- packages/module/src/styles/_dark-custom-override.scss
> Use same blue highlight for code tags outside of CodeBlock components

- packages/module/package.json
Closes https://github.com/patternfly/patternfly-quickstarts/issues/227
> chore(deps): Update peerDep for react-core to v5

- packages/module/src/catalog/QuickStartTile.tsx
The quickstarts panel is not opening on tile click. Only on the `Enter` key press. Currently, the click is sending different arguments in the event handler.
Also the CatalogTile is for some reason blocking the click handler. I've moved it to the parent div so it is triggering again.
> fix(quickstart tile): opening quickstarts on click event

- packages/dev/package.json
- packages/dev/src/CustomCatalog.tsx
- packages/module/src/catalog/QuickStartTile.tsx
- packages/module/src/catalog/QuickStartTileHeader.scss
- packages/module/src/catalog/QuickStartTileHeader.tsx
- yarn.lock
- Make cards clickable
- Fix card active/hover styling
- Open links in new tab
> Some post-PF5 fixes: Make cards clickable, fix card styling, open links in new tab

- packages/module/src/QuickStartPanelContent.tsx
- packages/module/src/controller/QuickStartTaskHeader.tsx
- packages/module/src/utils/quick-start-context.tsx
I'm working on an application that provides a UI for people making QuickStart files. As part of this, I'm trying to use `QuickStartDrawer` to render a preview of the QuickStart. However, if the QuickStart is a QuickStart with tasks, thus opening the side panel, whenever the values in the QuickStart are changed, the panel grabs focus.
For instance, if I have a textbox that allows editing the description of a QuickStart, the user will enter a character into the textbox. That will result in the QuickStart being changed in the `QuickStartContext`. This will propagate down to `QuickStartPanel` and trigger [this hook](https://github.com/randomnetcat/patternfly-quickstarts/blob/c6f8c67fa7789c480f85f08bce8c6239f3926b3d/packages/module/src/QuickStartPanelContent.tsx#L92-L96) and pull focus to the …
> Allow disabling quickstart panel grabbing focus

- packages/dev/src/quickstarts-data/yaml/template.yaml
Added link to Best Practices for quick starts doc to help content creators, updated the OCP docs link to version 4.16 (most recent)
> Update quick start template with style guides

- packages/module/patternfly-docs/content/extensions/quick-starts/design-guidelines/design-guidelines.md
Updated design-guidelines.md with a link to the definitive quick starts style/content guidelines, created by Red Hat UXD & docs teams. 
The aim of the UXD Hub resource is to combine the guidance from all the various guidelines/best practices for writing PatternFly quick starts to help folks create more consistent quick starts following a single source of truth, especially in the Red Hat Hybrid Cloud Console. See https://issues.redhat.com/browse/HCCDOC-2517 for more info on this initiative.
We've also pulled in the relevant guidelines into the UXD Hub doc from the OpenShift doc mentioned here, but since the OpenShift docs link contains additional helpful content that is needed by those working in that space, it seemed to make sense to include both links. 
Feel free to edit my wording or …
> Added link to UXD Hub content guidelines

- packages/module/src/QuickStartPanelContent.scss
- packages/module/src/catalog/QuickStartTileHeader.tsx
Fixes issue #342 by removing the extra title tag.
> fix: Fix for title size issue.

- packages/module/src/QuickStartCatalogPage.tsx
closes https://github.com/patternfly/patternfly-quickstarts/issues/359
before:
after:
> fix(QuickStartCatalogPage): remove extra spacing in title and hint

- package.json
- packages/dev/package.json
- packages/module/package.json
- packages/module/src/ConsoleInternal/components/markdown-view.tsx
- packages/module/src/QuickStartPanelContent.tsx
- packages/module/src/controller/QuickStartTaskHeader.tsx
- packages/module/src/declaration.d.ts
- yarn.lock
> chore(deps): Replace showdown dependency with marked

- packages/module/src/ConsoleInternal/components/markdown-view.tsx
v4 version of https://github.com/patternfly/patternfly-quickstarts/pull/373
> fix(markdown): fix plain code fences not being transformed

- packages/dev/src/AppCustomDrawer.tsx
- packages/dev/src/AppProps.tsx
- packages/dev/src/CustomCatalog.tsx
- packages/module/src/QuickStartCatalogPage.tsx
Fixes https://github.com/patternfly/patternfly/issues/7332
Minor adjustments to space buttons
**After**
**Current**
https://quickstarts.netlify.app/
> fix(quickstarts): restructure components to correct spacing and remove divider below toolbar

- packages/module/src/ConsoleShared/src/components/spotlight/InteractiveSpotlight.tsx
- packages/module/src/ConsoleShared/src/components/spotlight/StaticSpotlight.tsx
- packages/module/src/ConsoleShared/src/components/spotlight/spotlight.scss
OCP reported that the spotlight CSS was missing in PF6 causing their spotlight feature to cease to work in 4.19.
This PR returns the missing CSS
Before:
After:
> fix(spotlight): return missing scss file
