patternfly/patternfly-quickstarts

packages/dev/package.json
packages/dev/src/index.tsx
packages/dev/src/quickstarts-data/mocks/yamls/copy-execute-snippets.yaml
packages/dev/src/quickstarts-data/mocks/yamls/spring-with-s2i.yaml
packages/dev/src/quickstarts-data/quick-start-test-data.ts
packages/module/package.json
packages/module/rollup.config.js
packages/module/src/ConsoleInternal/bootstrap.scss
packages/module/src/ConsoleInternal/style/_base.scss
packages/module/src/ConsoleInternal/vendor.scss
packages/module/src/ConsoleShared/src/components/index.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/MarkdownCopyClipboard.tsx
packages/module/src/ConsoleShared/src/components/markdown-extensions/__tests__/MarkdownCopyClipboard.spec.tsx
packages/module/src/ConsoleShared/src/components/markdown-extensions/__tests__/test-data.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/const.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/index.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/inline-clipboard-extension.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/multiline-clipboard-extension.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/showdown-extension.scss
packages/module/src/ConsoleShared/src/components/markdown-extensions/utils.ts
packages/module/src/ConsoleShared/src/hooks/index.ts
packages/module/src/ConsoleShared/src/hooks/useEventListener.ts
packages/module/src/QuickStartMarkdownView.tsx
packages/module/src/QuickStartPanelContent.scss
packages/module/src/global.ts
packages/module/src/locales/en/quickstart.json
packages/module/src/overrides.ts

Also separate out global styles

Bring in the "copy extension"

---

packages/dev/package.json
packages/module/package.json
packages/module/src/QuickStartCatalogPage.tsx
packages/module/src/QuickStartPanelContent.tsx
packages/module/src/catalog/QuickStartTile.tsx
packages/module/src/catalog/QuickStartTileHeader.tsx
packages/module/src/controller/QuickStartFooter.tsx

https://github.com/openshift/console/pull/9347

merge OS PR 9347

---

packages/module/src/QuickStartCloseModal.tsx
packages/module/src/catalog/QuickStartTileHeader.tsx

Story: https://issues.redhat.com/browse/ODC-6008

Add datatest id's to QuickStartCloseModal.tsx and QuickStartTileHeader.tsx files

---

packages/module/src/catalog/QuickStartTile.tsx

Bug: https://issues.redhat.com/browse/ODC-6186

Added alt text to quick start icon to resolve accessibility issue

---

packages/dev/package.json
packages/module/package.json
packages/module/src/ConsoleInternal/components/markdown-view.tsx
packages/module/src/ConsoleInternal/components/utils/status-box.tsx
packages/module/src/ConsoleShared/src/components/modal/Modal.tsx
packages/module/src/ConsoleShared/src/components/status/StatusIconAndText.tsx
packages/module/src/QuickStartPanelContent.tsx
packages/module/src/controller/QuickStartTaskHeader.tsx
packages/module/src/controller/QuickStartTaskReview.tsx
yarn.lock

And remove the classnames package

Deps catalog view ext

---

packages/module/src/controller/QuickStartConclusion.tsx
packages/module/src/controller/QuickStartIntroduction.tsx
packages/module/src/controller/QuickStartTaskHeader.scss
packages/module/src/controller/QuickStartTaskHeader.tsx
packages/module/src/controller/QuickStartTaskHeaderList.scss
packages/module/src/controller/QuickStartTaskHeaderList.tsx
packages/module/src/controller/QuickStartTasks.scss
packages/module/src/controller/QuickStartTasks.tsx

https://issues.redhat.com/browse/ODC-6231
Accessibilty issue in listitems of QuickStartIntroduction
----------------------------------------------------------
Adds list to wrap listItems as direct children
-------------------------------------------------
before fix
----------------------------------------------------

fix list accessibilty issue

---

package.json

Has no issue, just a development nice to have.

feat(yarn): add watch:quick yarn script

---

packages/module/src/QuickStartPanelContent.tsx

feat(PanelContent): scroll top on back/next

---

packages/module/src/controller/QuickStartTaskHeader.scss
packages/module/src/controller/QuickStartTaskHeader.tsx

Closes: #53, #54, #55, #57
Toward: #29

Updates to numbered list of tasks in the drawer

---

packages/module/src/controller/QuickStartTaskHeader.scss
packages/module/src/controller/QuickStartTaskHeader.tsx

Task list: Failed task and icon red, skipped task icons numbers + "try steps again"

---

packages/dev/package.json
packages/module/package.json

Major version bump for visual updates

version 2.0

---

packages/dev/src/SettingsModal.tsx
packages/module/src/utils/quick-start-context.tsx

Default to always show Check Your Work section

---

packages/module/src/ConsoleInternal/components/markdown-view.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/108
This quick start for instance has several external links:
https://deploy-preview-115--quickstarts.netlify.app/?quickstart=getting-started-with-quick-starts

open links in new window

---

.github/workflows/a11y.yml
package.json
packages/dev/src/quickstarts-data/asciidoc/alert-note-prereq/README.adoc
packages/dev/src/quickstarts-data/asciidoc/alert-note-prereq/quickstart.yml
packages/dev/src/quickstarts-data/asciidoc/getting-started/README.adoc
packages/dev/src/quickstarts-data/asciidoc/getting-started/quickstart.yml
packages/dev/src/quickstarts-data/asciidoc/kafka-bin-scripts/README.adoc
packages/dev/src/quickstarts-data/asciidoc/kafka-bin-scripts/quickstart.yml
packages/module/src/controller/QuickStartTaskHeader.scss
packages/module/src/controller/QuickStartTaskHeader.tsx
packages/module/src/controller/QuickStartTaskReview.tsx
packages/module/src/controller/QuickStartTasks.tsx
patternfly-a11y.config.js

Closes #88
Added patternfly a11y script and fixed few issues.
We still need to figure out how to and where to upload the accessibility report.

Adding a11y script

---

packages/dev/src/quickstarts-data/asciidoc/alert-note-prereq/README.adoc
packages/dev/src/quickstarts-data/asciidoc/alert-note-prereq/quickstart.yml
packages/transform-adoc/src/react-converter/add-react-converter.tsx
packages/transform-adoc/src/react-converter/util.tsx
yarn.lock

Multi paragraph procedure, replace blocks

---

packages/transform-adoc/package.json

version bump transform-adoc

---

packages/dev/src/quickstarts-data/yaml/in-context-help/example-topics.yaml
packages/module/README.md
packages/module/src/HelpTopicDrawer.tsx
packages/module/src/HelpTopicPanelContent.tsx
packages/module/src/utils/help-topic-types.ts
yarn.lock

add helptopic links, cleanup

---

packages/module/README.md
packages/module/src/controller/QuickStartTaskHeader.tsx
packages/transform-adoc/src/react-converter/util.tsx

Fixes https://github.com/patternfly/patternfly-quickstarts/issues/170

fix some spelling mistakes

---

packages/dev/src/quickstarts-data/quick-start-test-data.ts
packages/dev/src/quickstarts-data/yaml/openshift-tabbed-copy.yaml
packages/module/src/ConsoleShared/src/components/markdown-extensions/inline-clipboard-extension.tsx

Update regex to pick up tabbed blocks

---

packages/module/src/ConsoleShared/src/components/markdown-extensions/admonition-extension.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/189

Relax admonition regex

---

.github/workflows/add-to-project.yml

Automatically add any new issues to the PatternFly Extensions project board.

Create workflow for new project board

---

packages/transform-adoc/src/react-converter/util.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/187

update text for task level prereqs

---

packages/module/src/controller/QuickStartTaskHeader.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/49

focus nav title on button click

---

packages/module/src/QuickStartPanelContent.tsx
packages/module/src/catalog/QuickStartTile.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/89
Creating follow up issue on what to do with focus when a drawer is closed

tabbable cards that can be opened

---

packages/dev/src/quickstarts-data/yaml/in-app-documentation/example-topics.yaml

Updated code to include a mark down example for users of quickstart.  Addresses issue #203

Updated mark down inline example with an alert example.

---

packages/dev/package.json
packages/dev/src/quickstarts-data/yaml/template.yaml
packages/module/package.json
packages/module/src/ConsoleShared/src/components/markdown-extensions/admonition-extension.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/211

support formatting within notes

---

packages/dev/src/quickstarts-data/yaml/openshift-tabbed-copy.yaml
packages/module/src/ConsoleShared/src/components/markdown-extensions/accordion-extension.tsx
packages/module/src/ConsoleShared/src/components/markdown-extensions/accordion-render-extension.tsx
packages/module/src/ConsoleShared/src/components/markdown-extensions/const.ts
packages/module/src/ConsoleShared/src/components/markdown-extensions/index.ts
packages/module/src/QuickStartMarkdownView.tsx

Accordion update for section support.

---

packages/dev/package.json
packages/module/package.json
packages/module/patternfly-docs/content/extensions/quick-starts/examples/about.md
packages/module/patternfly-docs/content/extensions/quick-starts/examples/basic.md
packages/module/patternfly-docs/content/extensions/quick-starts/examples/help-topics.md
yarn.lock

Current sourceLinks are causing 404 errors

chore(docs): Update sourceLinks for docs

---

.github/workflows/a11y.yml
.github/workflows/node.js.yml
.github/workflows/release.yml
.github/workflows/visual-testing.yml
packages/module/release.config.js

Setup v4 maintenance branch towards #243

chore(CI): Setup v4 branch to continue releasing to prerelease channel

---

packages/module/package.json
packages/module/release.config.js

Setup alpha release towards #243

chore(CI-release): Enable v5 release

---

packages/module/release.config.js

Towards #243
Tries to get semantic release onto the proper version number.

chore(CI-breaking): Increment package version

---

packages/dev/package.json
packages/module/package.json
packages/module/rollup.config.js
yarn.lock

Closes https://github.com/patternfly/patternfly-quickstarts/issues/262

Remove showdown as dependency, update peerDep version of showdown

---

packages/module/src/QuickStartController.tsx

Fixes the Continue button behavior, so it will only skip past the Succeeded tasks.
I think this also fixes https://github.com/patternfly/patternfly-quickstarts/issues/249
Closes https://github.com/patternfly/patternfly-quickstarts/issues/249
Before:

fix(continue): Fix continue button behavior

---

packages/dev/package.json
packages/module/package.json
packages/module/rollup.config.js
yarn.lock

(cherry picked from commit baed099ef57fb73d1c6873046ad07ddc3be5c459)

fix(deps): Remove showdown as dependency

---

.github/workflows/promote.yml
.github/workflows/release.yml
packages/module/package.json
packages/module/release.config.js
yarn.lock

Update CI and semantic release for the v6 branch

---

.github/workflows/add-to-project.yml

Updated github actions to create issues in [PatternFly Issues](https://github.com/orgs/patternfly/projects/7).

chore(pf-issues): Updated github actions to add to pf issues.

---

packages/dev/src/quickstarts-data/yaml/template.yaml

Closes: https://github.com/patternfly/patternfly-quickstarts/issues/301
Updating a v4 link in the YAML template file.

fix(yaml template): update v5 link

---

packages/dev/package.json
packages/dev/src/CustomCatalog.tsx
packages/module/package.json
packages/module/patternfly-docs/content/extensions/quick-starts/design-guidelines/design-guidelines.md
packages/module/release.config.js
packages/module/src/catalog/QuickStartCatalog.tsx
packages/module/src/catalog/QuickStartTile.tsx
packages/module/src/catalog/QuickStartTileHeader.tsx
packages/module/src/catalog/__tests__/QuickStartTile.spec.tsx
packages/module/src/controller/QuickStartFooter.tsx
packages/module/src/controller/QuickStartTaskHeaderList.tsx
yarn.lock

Replace https://github.com/patternfly/patternfly-quickstarts/pull/326

docs(design-guidelines): Updated quickstarts guidelines.

---

package.json
packages/dev/package.json
packages/module/package.json
packages/vscode/package.json
yarn.lock

Updated to the latest prerelease.

fix: Updated to the latest prerelease versions.

---

packages/dev/package.json
packages/dev/src/CustomCatalog.tsx
packages/module/package.json
packages/module/src/catalog/QuickStartCatalog.tsx
packages/module/src/catalog/QuickStartTileHeader.tsx
packages/module/src/controller/QuickStartTaskHeaderList.tsx
packages/module/src/controller/QuickStartTasks.tsx
packages/vscode/package.json
yarn.lock

fix: bump to release candidate versions

---

package.json
packages/module/src/controller/QuickStartContent.scss
yarn.lock

Closes: https://github.com/patternfly/patternfly-quickstarts/issues/353

fix: fix height of steps

---

packages/dev/package.json
packages/module/package.json
packages/module/src/ConsoleInternal/components/markdown-view.tsx
yarn.lock

chore(deps): Replace showdown dependency with marked

---

packages/dev/package.json
packages/vscode/package.json
yarn.lock

Updated to the latest version of i18next.

fix: Updated to latest version of i18next

---

packages/module/patternfly-docs/content/extensions/quick-starts/design-guidelines/design-guidelines.md

Fixes design page from throwing an exception and crashing when navigating to it on patternfly.org

fix: Fixes design page exception

---

packages/module/package.json

Updated react dom for compatibility issues.

fix: updated react dom.

---

packages/module/src/QuickStartDrawerContent.tsx

Closes https://github.com/patternfly/patternfly-quickstarts/issues/401

fix(QSDrawerContent): prevent duplication of qs in drawer content
